spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off
---
# local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    mariadb:
      hikari:
        minimum-idle: 50
        maximum-pool-size: 400
        auto-commit: false
        connection-timeout: 58000
        max-lifetime: 580000
